Videoclub.Web/Areas/Customers/Models/CustomerBindingModel.cs
namespace Videoclub.Web.Areas.Customers.Models
{
    public class CustomerBindingModel
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public int ActiveRentals { get; set; }
        public string ApplicationUserId { get; set; }

        public CustomerBindingModel(string firstName, string lastName, string email, int activeRentals, string applicationUserId)
        {
            FirstName = firstName;
            LastName = lastName;
            Email = email;
            ActiveRentals = activeRentals;
            ApplicationUserId = applicationUserId;
        }

        public CustomerBindingModel()
        {
            
        }
    }
}

Videoclub.Web/Areas/Customers/Models/CustomerViewModel.cs
using System.ComponentModel.DataAnnotations;
using Videoclub.Core.Entities;

namespace Videoclub.Web.Areas.Customers.Models
{
    public class CustomerViewModel
    {
        [Display(Name = "First Name")]
        public string FirstName { get; set; }

        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        public string  Email { get; set; }

        [Display(Name = "Active Rentals")]
        public int  NumberOfActiveRentals { get; set; }

        public string ApplicationUserId { get; set; }

        public CustomerViewModel(Customer customer)
        {
            FirstName = customer.FirstName;
            LastName = customer.LastName;
            Email = customer.Email;
            NumberOfActiveRentals = customer.NumberOfActiveRentals;
            ApplicationUserId = customer.ApplicationUserId;
        }
    }
}

Videoclub.Web/Areas/Customers/Controllers/CustomersController.cs
using System;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using OfficeOpenXml;
using Videoclub.Core.Interfaces;
using Videoclub.Web.Areas.Customers.Models;
using Videoclub.Web.Areas.Rentals.Models;

namespace Videoclub.Web.Areas.Customers.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CustomersController : Controller
    {
        private readonly ICustomerService _customersDb;

        public CustomersController()
        {
            
        }

        public CustomersController(ICustomerService customersDb)
        {
            _customersDb = customersDb;
        }

        [HttpGet]
        public ActionResult Index()
        {
            var customers = _customersDb.GetAllCustomers();
            var model = customers.Select(customer => new CustomerViewModel(customer)).ToList();

            return View(model);
        }

        [HttpGet]
        public ActionResult ExportCustomers()
        {
            var customers = _customersDb.GetAllCustomers();
            ExcelPackage.LicenseContext = LicenseContext.NonCommercial;

            using (var package = new ExcelPackage())
            {
                var worksheet = package.Workbook.Worksheets.Add("customers");
                worksheet.Cells[1, 1].Value = "ID";
                worksheet.Cells[1, 2].Value = "F_NAME";
                worksheet.Cells[1, 3].Value = "L_NAME";
                worksheet.Cells[1, 4].Value = "EMAIL";
                worksheet.Cells[1, 5].Value = "ACTIVE_RENTALS";
                worksheet.Cells[1, 6].Value = "FAVOURITES";

                var rowIndex = 2;

                foreach (var customer in customers)
                {
                    worksheet.Cells[rowIndex, 1].Value = customer.ApplicationUserId;
                    worksheet.Cells[rowIndex, 2].Value = customer.FirstName;
                    worksheet.Cells[rowIndex, 3].Value = customer.LastName;
                    worksheet.Cells[rowIndex, 4].Value = customer.Email;
                    worksheet.Cells[rowIndex, 5].Value = customer.NumberOfActiveRentals;
                    worksheet.Cells[rowIndex, 6].Value = customer.Favourites;

                    rowIndex++;
                }

                worksheet.Cells.AutoFitColumns();


                var stream = new MemoryStream();
                package.SaveAs(stream);
                stream.Seek(0, SeekOrigin.Begin);

                return File(
                    stream,
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                    "Videoclub_customers.xlsx"
                );
            }
        }

        [HttpGet]
        public ActionResult DeleteCustomer(string id)
        {
            var customer = _customersDb.GetCustomer(id);
            var model = new CustomerViewModel(customer);

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteCustomer(string id, FormCollection form)
        {
            var customer = _customersDb.GetCustomer(id);

            if (customer != null)
            {
                _customersDb.DeleteCustomer(customer.ApplicationUserId);

                return RedirectToAction("Index");
            }

            return View();
        }

        [HttpGet]
        public ActionResult CustomerRentals(string id)
        {
            var customerRentals = _customersDb.GetRentalsOfCustomer(id);
            var model = customerRentals.Select(rental => new RentalViewModel(rental)).ToList();

            ViewBag.TotalRentals = model.Count();
            ViewBag.CustomerEmail = _customersDb.GetCustomer(id).Email;
            ViewBag.CustomerId = id;

            return View(model);
        }

        [HttpGet]
        public ActionResult ExportCustomerRentals(string id)
        {
            var customerRentals = _customersDb.GetRentalsOfCustomer(id);
            ExcelPackage.LicenseContext = LicenseContext.NonCommercial;

            using (var package = new ExcelPackage())
            {
                var worksheet = package.Workbook.Worksheets.Add("customer_rentals");
                worksheet.Cells[1, 1].Value = "ID";
                worksheet.Cells[1, 2].Value = "DATE_RENTED";
                worksheet.Cells[1, 3].Value = "DATE_RETURNED";
                worksheet.Cells[1, 4].Value = "IS_ACTIVE";
                worksheet.Cells[1, 5].Value = "TITLE";
                worksheet.Cells[1, 6].Value = "COPY_ID";
                worksheet.Cells[1, 7].Value = "COMMENT";

                var rowIndex = 2;

                foreach (var rental in customerRentals)
                {
                    worksheet.Cells[rowIndex, 1].Value = rental.Id;
                    worksheet.Cells[rowIndex, 2].Value = $"{rental.DateRented:dd-MM-yyyy HH:mm}";
                    worksheet.Cells[rowIndex, 3].Value = $"{rental.ReturnDate:dd-MM-yyyy HH:mm}";
                    worksheet.Cells[rowIndex, 4].Value = rental.IsActive;
                    worksheet.Cells[rowIndex, 5].Value = rental.Copy.Movie.Title;
                    worksheet.Cells[rowIndex, 6].Value = rental.CopyId;
                    worksheet.Cells[rowIndex, 7].Value = rental.Comment;

                    rowIndex++;
                }

                worksheet.Cells.AutoFitColumns();


                var stream = new MemoryStream();
                package.SaveAs(stream);
                stream.Seek(0, SeekOrigin.Begin);

                return File(
                    stream,
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                    $"{customerRentals.First().Customer.Email}_rentals.xlsx"
                );
            }
        }
    }
}

Videoclub.Web/Areas/Customers/Views/Customers/CustomerRentals.cshtml
@using System.Web.UI.WebControls
@model IEnumerable<Videoclub.Web.Areas.Rentals.Models.RentalViewModel>

@{
    ViewBag.Title = "CustomerRentals";
}

<h2>CustomerRentals</h2>

<br/>

<h3>Customer @ViewBag.CustomerEmail has @ViewBag.TotalRentals rentals</h3>

<br/>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.MovieTitle)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CopyId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateRented)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ReturnDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsActive)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Comment)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.MovieTitle)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CopyId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateRented)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ReturnDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsActive)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Comment)
            </td>
        </tr>
    }

</table>


<br/>

<div>
    <a href="@Url.Action("ExportCustomerRentals", "Customers", new { id = @ViewBag.CustomerId })" class="btn btn-default btn-barilla">EXPORT CUSTOMER RENTALS</a>
</div>

Videoclub.Web/Areas/Customers/Views/Customers/DeleteCustomer.cshtml
@model Videoclub.Web.Areas.Customers.Models.CustomerViewModel

@{
    ViewBag.Title = "DeleteCustomer";
}

<h2>DeleteCustomer</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CustomerViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NumberOfActiveRentals)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumberOfActiveRentals)
        </dd>

        @Html.HiddenFor(model => model.ApplicationUserId)

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Videoclub.Web/Areas/Customers/Views/Customers/Index.cshtml
@model IEnumerable<Videoclub.Web.Areas.Customers.Models.CustomerViewModel>

@{
    ViewBag.Title = "Index";
}

<h2>List of all customers</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NumberOfActiveRentals)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NumberOfActiveRentals)
            </td>
            <td>
                @Html.ActionLink("Customer Rentals", "CustomerRentals", new { id = item.ApplicationUserId }) |
                @Html.ActionLink("Delete Customer", "DeleteCustomer", new { id = item.ApplicationUserId })
            </td>
        </tr>
    }

</table>

<br/>
<br />

<div>
    <a href="@Url.Action("ExportCustomers", "Customers")" class="btn btn-default btn-barilla">EXPORT CUSTOMERS</a>
</div>