Videoclub.Web/Areas/Rentals/Models/RentalBindingModel.cs
using System.ComponentModel.DataAnnotations;

namespace Videoclub.Web.Areas.Rentals.Models
{
    public class RentalBindingModel
    {
        [Required]
        [Display(Name = "Movie Title")]
        public string MovieTitle { get; set; }

        [Required]
        [Display(Name = "Customer Email")]
        public string CustomerEmail { get; set; }

        public string Comment { get; set; }

        public RentalBindingModel(string movieTitle)
        {
            MovieTitle = movieTitle;
        }

        public RentalBindingModel()
        {
            
        }
    }
}

Videoclub.Web/Areas/Rentals/Models/RentalViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;
using Videoclub.Core.Entities;

namespace Videoclub.Web.Areas.Rentals.Models
{
    public class RentalViewModel
    {
        public int Id { get; set; }

        [Display(Name = "Movie Title")]
        public string MovieTitle { get; set; }

        [Display(Name = "Copy ID")]
        public int CopyId { get; set; }

        [Display(Name = "Date Rented")]
        public DateTime DateRented { get; set; }

        [Display(Name = "Return Date")]
        public DateTime ReturnDate { get; set; }

        [Display(Name = "Is Active")]
        public bool IsActive { get; set; }

        public string Comment { get; set; }

        [Display(Name = "Customer Email")]
        public string CustomerEmail { get; set; }

        public RentalViewModel()
        {
            
        }

        public RentalViewModel(Rental rental)
        {
            Id = rental.Id;
            MovieTitle = rental.Copy.Movie.Title;
            CopyId = rental.CopyId;
            DateRented = rental.DateRented;
            ReturnDate = rental.ReturnDate;
            IsActive = rental.IsActive;
            Comment = rental.Comment;
            CustomerEmail = rental.Customer.Email;
        }
    }
}

Videoclub.Web/Areas/Rentals/Models/ReturnBindingModel.cs
using System.ComponentModel.DataAnnotations;

namespace Videoclub.Web.Areas.Rentals.Models
{
    public class ReturnBindingModel
    {
        [Required]
        [Display(Name = "Movie Title")]
        public string MovieTitle { get; set; }

        [Required]
        [Display(Name = "Customer Email")]
        public string CustomerEmail { get; set; }

        public string Comment { get; set; }

        public int RentalId { get; set; }

        public ReturnBindingModel(string movieTitle, string customerEmail, int rentalId)
        {
            MovieTitle = movieTitle;
            CustomerEmail = customerEmail;
            RentalId = rentalId;
        }

        public ReturnBindingModel()
        {
            
        }
    }
}

Videoclub.Web/Areas/Rentals/Controllers/RentalsController.cs
using System.IO;
using System.Linq;
using System.Web.Mvc;
using OfficeOpenXml;
using Videoclub.Core.Entities;
using Videoclub.Core.Interfaces;
using Videoclub.Web.Areas.Rentals.Models;

namespace Videoclub.Web.Areas.Rentals.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RentalsController : Controller
    {
        private readonly IRentalService _rentalsDb;
        private readonly IReturnService _returnsDb;
        private readonly ICopyService _copiesDb;
        private readonly ICustomerService _customersDb;

        public RentalsController()
        {
            
        }

        public RentalsController(IRentalService rentalsDb, IReturnService returnsDb, ICopyService copiesDb, ICustomerService customersDb)
        {
            _rentalsDb = rentalsDb;
            _returnsDb = returnsDb;
            _copiesDb = copiesDb;
            _customersDb = customersDb;
        }

        [HttpGet]
        public ActionResult Index()
        {
            var activeRentals = _rentalsDb.GetAllActiveRentals();
            var model = activeRentals.Select(rental => new RentalViewModel(rental)).ToList();

            return View(model);
        }

        [HttpGet]
        public ActionResult ExportActiveRentals()
        {
            var rentals = _rentalsDb.GetAllActiveRentals();
            ExcelPackage.LicenseContext = LicenseContext.NonCommercial;

            using (var package = new ExcelPackage())
            {
                var worksheet = package.Workbook.Worksheets.Add("all_rentals");
                worksheet.Cells[1, 1].Value = "ID";
                worksheet.Cells[1, 2].Value = "CUSTOMER";
                worksheet.Cells[1, 3].Value = "DATE_RENTED";
                worksheet.Cells[1, 4].Value = "DATE_RETURNED";
                worksheet.Cells[1, 5].Value = "IS_ACTIVE";
                worksheet.Cells[1, 6].Value = "TITLE";
                worksheet.Cells[1, 7].Value = "COPY_ID";
                worksheet.Cells[1, 8].Value = "COMMENT";

                var rowIndex = 2;

                foreach (var rental in rentals)
                {
                    worksheet.Cells[rowIndex, 1].Value = rental.Id;
                    worksheet.Cells[rowIndex, 2].Value = rental.Customer.Email;
                    worksheet.Cells[rowIndex, 3].Value = $"{rental.DateRented:dd-MM-yyyy HH:mm}";
                    worksheet.Cells[rowIndex, 4].Value = $"{rental.ReturnDate:dd-MM-yyyy HH:mm}";
                    worksheet.Cells[rowIndex, 5].Value = rental.IsActive;
                    worksheet.Cells[rowIndex, 6].Value = rental.Copy.Movie.Title;
                    worksheet.Cells[rowIndex, 7].Value = rental.CopyId;
                    worksheet.Cells[rowIndex, 8].Value = rental.Comment;

                    rowIndex++;
                }

                worksheet.Cells.AutoFitColumns();


                var stream = new MemoryStream();
                package.SaveAs(stream);
                stream.Seek(0, SeekOrigin.Begin);

                return File(
                    stream,
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                    "Videoclub_rentals.xlsx"
                );
            }
        }

        public ActionResult ExportReturns()
        {
            var returns = _returnsDb.GetAllReturns();
            ExcelPackage.LicenseContext = LicenseContext.NonCommercial;

            using (var package = new ExcelPackage())
            {
                var worksheet = package.Workbook.Worksheets.Add("all_returns");
                worksheet.Cells[1, 1].Value = "ID";
                worksheet.Cells[1, 2].Value = "CUSTOMER";
                worksheet.Cells[1, 3].Value = "EXPECTED_RETURN_DATE";
                worksheet.Cells[1, 4].Value = "ACTUAL_RETURN_DATE";
                worksheet.Cells[1, 5].Value = "TITLE";
                worksheet.Cells[1, 6].Value = "COPY_ID";
                worksheet.Cells[1, 7].Value = "COMMENT";

                var rowIndex = 2;

                foreach (var rentalReturn in returns)
                {
                    worksheet.Cells[rowIndex, 1].Value = rentalReturn.Id;
                    worksheet.Cells[rowIndex, 2].Value = rentalReturn.Customer.Email;
                    worksheet.Cells[rowIndex, 3].Value = $"{rentalReturn.ActualReturnDate:dd-MM-yyyy HH:mm}";
                    worksheet.Cells[rowIndex, 4].Value = $"{rentalReturn.ExpectedReturnDate:dd-MM-yyyy HH:mm}";
                    worksheet.Cells[rowIndex, 5].Value = rentalReturn.Copy.Movie.Title;
                    worksheet.Cells[rowIndex, 6].Value = rentalReturn.CopyId;
                    worksheet.Cells[rowIndex, 7].Value = rentalReturn.Comment;

                    rowIndex++;
                }

                worksheet.Cells.AutoFitColumns();


                var stream = new MemoryStream();
                package.SaveAs(stream);
                stream.Seek(0, SeekOrigin.Begin);

                return File(
                    stream,
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                    "Videoclub_returns.xlsx"
                );
            }
        }

        [HttpGet]
        public ActionResult ReturnRental(int id)
        {
            var rental = _rentalsDb.GetRental(id);
            var model = new ReturnBindingModel(rental.Copy.Movie.Title, rental.Customer.Email, rental.Id);

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ReturnRental(ReturnBindingModel model)
        {
            var rental = _rentalsDb.GetRental(model.RentalId);
            var rentalReturn = new Return(rental.ReturnDate, model.Comment, rental.CustomerId, rental.CopyId);

            _returnsDb.AddReturn(rentalReturn);
            _rentalsDb.SetRentalInactive(rental);
            _copiesDb.SetCopyAvailable(rental.CopyId);
            _customersDb.DecreaseActiveRentals(rental.CustomerId);

            return RedirectToAction("Index");
        }
    }
}

Videoclub.Web/Areas/Rentals/Views/Rentals/Index.cshtml
@model IEnumerable<Videoclub.Web.Areas.Rentals.Models.RentalViewModel>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CustomerEmail)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MovieTitle)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateRented)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ReturnDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsActive)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Comment)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CustomerEmail)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MovieTitle)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateRented)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ReturnDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsActive)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Comment)
            </td>

            <td>
                @Html.ActionLink("Return Rental", "ReturnRental", new { id = item.Id })
            </td>
    
        </tr>
    }

</table>

<br/>
<br/>

<div>
    <a href="@Url.Action("ExportActiveRentals", "Rentals")" class="btn btn-default btn-barilla">EXPORT ACTIVE RENTALS</a>
</div>

<br />

<div>
    <a href="@Url.Action("ExportReturns", "Rentals")" class="btn btn-default btn-barilla">EXPORT RETURNS</a>
</div>

Videoclub.Web/Areas/Rentals/Views/Rentals/ReturnRental.cshtml
@model Videoclub.Web.Areas.Rentals.Models.ReturnBindingModel

@{
    ViewBag.Title = "ReturnRental";
}

<h2>ReturnRental</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>ReturnBindingModel</h4>

        @Html.HiddenFor(model => model.RentalId)

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.MovieTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MovieTitle, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.MovieTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerEmail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustomerEmail, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.CustomerEmail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Comment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Comment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Comment, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Submit" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>