Videoclub.Web/Areas/Movies/Models/MovieBindingModel.cs
using System.ComponentModel.DataAnnotations;
using Videoclub.Core.Enumerations;

namespace Videoclub.Web.Areas.Movies.Models
{
    public class MovieBindingModel
    {
        public int  MovieId { get; set; }

        [Required]
        public string Title { get; set; }

        [Required]
        public string Description { get; set; }

        [Required]
        public MovieGenre Genre { get; set; }

        [Required]
        [Display(Name = "No. of Copies")]
        public int NumberOfCopies { get; set; }

        public MovieBindingModel(string title, string description, MovieGenre genre, int numberOfCopies)
        {
            Title = title;
            Description = description;
            Genre = genre;
            NumberOfCopies = numberOfCopies;
        }

        public MovieBindingModel(int id, string title, string description, MovieGenre genre, int numberOfCopies)
        {
            MovieId = id;
            Title = title;
            Description = description;
            Genre = genre;
            NumberOfCopies = numberOfCopies;
        }

        public MovieBindingModel()
        {
            
        }
    }
}

Videoclub.Web/Areas/Movies/Models/MovieViewModel.cs
using System.Collections.Generic;
using Videoclub.Core.Entities;
using Videoclub.Core.Enumerations;

namespace Videoclub.Web.Areas.Movies.Models
{
    public class MovieViewModel
    {
        public int MovieId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public MovieGenre Genre { get; set; }
        public int NumberOfCopies { get; set; }
        public ICollection<Copy> Copies { get; set; }

        public MovieViewModel(Movie movie)
        {
            MovieId = movie.MovieId;
            Title = movie.Title;
            Description = movie.Description;
            Genre = movie.Genre;
            NumberOfCopies = movie.NumberOfCopies;
            Copies = movie.Copies;
        }
    }
}

Videoclub.Web/Areas/Movies/Controllers/MoviesController.cs
using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using PagedList;
using Videoclub.Core.Entities;
using Videoclub.Core.Interfaces;
using Videoclub.Infrastructure.Services.Interfaces;
using Videoclub.Web.Areas.Movies.Models;
using Videoclub.Web.Areas.Rentals.Models;
using OfficeOpenXml;

namespace Videoclub.Web.Areas.Movies.Controllers
{
    public class MoviesController : Controller
    {
        private readonly IMovieService _moviesDb;
        private readonly ICopyService _copiesDb;
        private readonly IRentalService _rentalsDb;
        private readonly ICustomerService _customersDb;
        private readonly ILoggingService _loggingService;

        public MoviesController()
        {
            
        }

        public MoviesController(IMovieService moviesDb, ICopyService copiesDb, IRentalService rentalsDb, ICustomerService customersDb, ILoggingService loggingService)
        {
            _moviesDb = moviesDb;
            _copiesDb = copiesDb;
            _rentalsDb = rentalsDb;
            _customersDb = customersDb;
            _loggingService = loggingService;
        }

        [HttpGet]
        [Authorize(Roles = "Admin, Customer")]
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var movies = _moviesDb.GetAllMovies();

            if (!String.IsNullOrEmpty(searchString))
            {
                movies = movies.Where(m => m.Title.Contains(searchString));
            }

            switch (sortOrder)
            {
                case "title_desc":
                    movies = movies.OrderByDescending(m => m.Title);
                    break;
                case "Genre":
                    movies = movies.OrderBy(m => m.Genre);
                    break;
                case "genre_desc":
                    movies = movies.OrderByDescending(m => m.Genre);
                    break;
                default:
                    movies = movies.OrderBy(m => m.Title);
                    break;
            }

            int moviesPerPage = 3;
            int pageNumber = (page ?? 1);

            ViewBag.MoviesCount = movies.Count();

            var model = movies.Select(movie => new MovieViewModel(movie)).ToList();

            return View(model.ToPagedList(pageNumber, moviesPerPage));
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public ActionResult ExportMovies()
        {
            var movies = _moviesDb.GetAllMovies();

            ExcelPackage.LicenseContext = LicenseContext.NonCommercial;

            using (var package = new ExcelPackage())
            {
                var worksheet = package.Workbook.Worksheets.Add("movies");
                worksheet.Cells[1, 1].Value = "ID";
                worksheet.Cells[1, 2].Value = "TITLE";
                worksheet.Cells[1, 3].Value = "DESCRIPTION";
                worksheet.Cells[1, 4].Value = "GENRE";
                worksheet.Cells[1, 5].Value = "COPIES";

                var rowIndex = 2;
                foreach (var movie in movies)
                {
                    worksheet.Cells[rowIndex, 1].Value = movie.MovieId;
                    worksheet.Cells[rowIndex, 2].Value = movie.Title;
                    worksheet.Cells[rowIndex, 3].Value = movie.Description;
                    worksheet.Cells[rowIndex, 4].Value = movie.Genre;
                    worksheet.Cells[rowIndex, 5].Value = movie.Copies.Count;

                    rowIndex++;
                }

                worksheet.Cells.AutoFitColumns();


                var stream = new MemoryStream();
                package.SaveAs(stream);
                stream.Seek(0, SeekOrigin.Begin);

                return File(
                    stream,
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                    "Videoclub_Movies_Export.xlsx"
                );
            }
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public ActionResult AddMovie()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult AddMovie(MovieBindingModel model)
        {
            var movie = new Movie(model.Title, model.Description, model.Genre, model.NumberOfCopies);

            if (_moviesDb.MovieAlreadyExists(movie.Title))
            {
                _loggingService.Info("Movie {Title} already exists! Can't add.", movie.Title);
                return View("~/Areas/Movies/Views/Movies/MovieAlreadyExists.cshtml");
            }

            _moviesDb.AddMovieInDb(movie);
            _copiesDb.AddCopiesOfMovie(movie.NumberOfCopies, movie.MovieId);

            _loggingService.Info("Movie {Title} added in DB!", movie.Title);

            return RedirectToAction("Index");
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public ActionResult UpdateMovie(int id)
        {
            var movie = _moviesDb.GetMovie(id);
            var model = new MovieBindingModel(movie.MovieId, movie.Title, movie.Description, movie.Genre, movie.NumberOfCopies);

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult UpdateMovie(MovieBindingModel model)
        {
            var movie = new Movie(model.MovieId, model.Title, model.Description, model.Genre, model.NumberOfCopies);
            _moviesDb.UpdateMovie(movie);

            return RedirectToAction("Index");
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteMovie(int id)
        {
            var movie = _moviesDb.GetMovie(id);
            var model = new MovieViewModel(movie);

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteMovie(int id, FormCollection form)
        {
            _moviesDb.DeleteMovie(id);

            return RedirectToAction("Index");
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public ActionResult RentMovie(int id)
        {
            var movie = _moviesDb.GetMovie(id);
            var model = new RentalBindingModel(movie.Title);

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult RentMovie(RentalBindingModel model)
        {
            var customer = _customersDb.GetCustomerByEmail(model.CustomerEmail);

            if (customer != null)
            {
                var movie = _moviesDb.GetMovieByTitle(model.MovieTitle);
                var copy = _copiesDb.GetAvailableCopy(movie.MovieId);
                var rental = new Rental(copy.CopyId, model.Comment, customer.ApplicationUserId);

                _rentalsDb.AddRental(rental);
                _copiesDb.SetCopyUnavailable(copy.CopyId);
                _customersDb.IncreaseActiveRentals(customer.ApplicationUserId);

                return RedirectToAction("Index");
            }

            ViewBag.Email = model.CustomerEmail;
            return View("~/Areas/Movies/Views/Movies/CustomerDoesntExist.cshtml");
        }
    }
}

Videoclub.Web/Areas/Movies/Views/Movies/AddMovie.cshtml
@model Videoclub.Web.Areas.Movies.Models.MovieBindingModel

@{
    ViewBag.Title = "AddMovie";
}

<h2>AddMovie</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>MovieBindingModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Genre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Genre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Genre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NumberOfCopies, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumberOfCopies, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumberOfCopies, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Videoclub.Web/Areas/Movies/Views/Movies/CustomerDoesntExist.cshtml
@{
    ViewBag.Title = "CustomerDoesntExist";
}

<h2 style="color: red;">No customer was found with email: @ViewBag.Email</h2>

Videoclub.Web/Areas/Movies/Views/Movies/DeleteMovie.cshtml
@model Videoclub.Web.Areas.Movies.Models.MovieViewModel

@{
    ViewBag.Title = "DeleteMovie";
}

<h2>DeleteMovie</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>MovieViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.HiddenFor(model => model.MovieId)
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Genre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Genre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NumberOfCopies)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumberOfCopies)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Videoclub.Web/Areas/Movies/Views/Movies/Index.cshtml
@model PagedList.IPagedList<Videoclub.Web.Areas.Movies.Models.MovieViewModel>
@using PagedList.Mvc;



@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

@if (User.IsInRole("Admin"))
{
    <p>
        @Html.ActionLink("Add new movie", "AddMovie")
    </p>
}

@using (Html.BeginForm("Index", "Movies", FormMethod.Get))
{
    <p>
        Search by Title: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        <input type="submit" value="Search" />
    </p>
}

<br>

<h4>@ViewBag.MoviesCount movies found</h4>

<h6>@ViewBag.Error</h6>

<table class="table">
    <tr>
        <th>
            @Html.ActionLink("Title", "Index", new { sortOrder = ViewBag.TitleSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            Description
        </th>
        <th>
            @Html.ActionLink("Genre", "Index", new { sortOrder = ViewBag.GenreSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            Available Copies
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Genre)
            </td>

            @{
                var availableCopiesCounter = 0;
            }

            @foreach (var copy in item.Copies)
            {
                if (copy.IsAvailable)
                {
                    availableCopiesCounter++;
                }
            }

            <td>
                @Html.Raw(availableCopiesCounter) /
                @Html.DisplayFor(modelItem => item.Copies.Count)
            </td>

            @if (User.IsInRole("Admin"))
            {
                <td>
                    @if (availableCopiesCounter > 0)
                    {
                        @Html.ActionLink("Rent Movie", "RentMovie", new { id = item.MovieId })
                    }
                    else
                    {
                        <p style="font-size: 14px; color: grey; display: inline;">Unavailable</p>
                    }
                    | @Html.ActionLink("Edit Movie", "UpdateMovie", new { id = item.MovieId }) |
                    @Html.ActionLink("Delete Movie", "DeleteMovie", new { id = item.MovieId })
                </td>
            }
        </tr>
    }
</table>

<br/>
<br />

<div>
    <a href="@Url.Action("ExportMovies", "Movies")" class="btn btn-default btn-barilla">EXPORT MOVIES</a>
</div>

<br />
<br />
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) out of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))

Videoclub.Web/Areas/Movies/Views/Movies/MovieAlreadyExists.cshtml
@{
    ViewBag.Title = "MovieAlreadyExists";
}

<h2>This movie already exists!</h2>

@*@Html.ActionLink("Back to List", "Index", "Movies")*@

Videoclub.Web/Areas/Movies/Views/Movies/RentMovie.cshtml
@model Videoclub.Web.Areas.Rentals.Models.RentalBindingModel

@{
    ViewBag.Title = "RentMovie";
}

<h2>RentMovie</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>MovieViewModel</h4>
        <hr />

        <div class="form-group">
            @Html.LabelFor(model => model.MovieTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MovieTitle, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.MovieTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerEmail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustomerEmail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustomerEmail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Comment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Comment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Comment, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Submit" class="btn btn-default" />
            </div>
        </div>

    </div>
}
<p>
    @Html.ActionLink("Back to List", "Index")
</p>

Videoclub.Web/Areas/Movies/Views/Movies/UpdateMovie.cshtml
@model Videoclub.Web.Areas.Movies.Models.MovieBindingModel

@{
    ViewBag.Title = "UpdateMovie";
}

<h2>UpdateMovie</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>MovieBindingModel</h4>

        @Html.HiddenFor(model => model.MovieId)

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Genre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Genre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Genre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NumberOfCopies, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumberOfCopies, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumberOfCopies, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}